### ISSUE TITLE
Quota Panel not updating and showing incorrect values

### ISSUE THREAD

**Issue by Keridos** [Gorea235/TaledensInvManagerUpdated#4] opened 2018-02-06 02:36 UTC
Having an LCD Panel here with a "[TIM QUOTA:Component]" Tag but the quota only updates once, and shows minimum values for everything.

**Comment by Gorea235** [comment] 2018-02-06 18:48
The quota panels are for showing and editing the current quota settings, not for showing the amount of items currently in the system. Is there a problem with quota values not updating when the panel is edited, or are you looking for the panel to show the current levels? The latter will need to be done with a separate script (such as Automatic LCDs)

**Comment by Gorea235** [comment] 2018-02-18 20:46
If it's not an issue with something else, then I'll close the issue, otherwise I will need to know where the problem is specifically

**Closed** 2018-02-22 14:14 UTC
Labels: wontfix
